name: rougecodes
description: "A learning app by RougeCodes"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flex_seed_scheme: ^3.5.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.3.2
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  flexible_wrap: ^1.0.7
  url_launcher: ^6.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
       - assets/images/rougecodes.png

# App icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appicon.png"
